### ISSUE TITLE
Per World Default Respawnlocation

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#141]
I'd like to be able to configure the default respawnlocation for a world so that a setup like this is possible without having to listen for PlayerRespawnEvent:
![Diagrams are awesome](http://puu.sh/jH70g/d77aaec5bc.png)

**Comment by gabizou** [comment]
More than likely can set this in `WorldProperties`.

**Comment by simon816** [comment]
I don't see why you wouldn't listen to `PlayerRespawnEvent` since it is the appropriate event for this kind of thing.
`Dimension` has `allowsPlayerRespawns()`, if that is true, the player will respawn in the same dimension they died in, otherwise it will send them to the overworld.
Simply use the event to change this, as the event will overrule anything already set.

**Comment by modwizcode** [comment]
Agreed. Some things are a better implemented through events even though they have traditionally been conceptualized as properties.

**Comment by gabizou** [comment]
If this is still something desired, quite literally needs to be exposed in the API, not implementation.
