### ISSUE TITLE
Properly fix profile resolver on the client so builtin permissions work properly

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeCommon#160]
@bloodmc has a quick hackfix, but this should be fixed properly so clients don't have issues with some permissions setups.

**Comment by simon816** [comment]
This should fix it: fbd36216718b7711c8ed3f12f72f10377815bc2e

**Comment by gabizou** [comment]
@simon816 did those commits actually fix the issue?

**Comment by simon816** [comment]
It did, but has since been commented out: https://github.com/SpongePowered/SpongeCommon/commit/eeddcb1bb9faa6d188560ea9b26a95c8842bf7a7#diff-8560402e5ab8aa9de45f947a0ce49b95

I also fixed an issue in forge related to this, and it seems to work fine now on the client.
So I guess the only thing left to do is to either move or remove the client code in `SpongeProfileResolver`

**Comment by gabizou** [comment]
@simon816 if the code is not needed anymore, just remove it and close this issue.

**Comment by simon816** [comment]
Yeah I'll remove it.
