### ISSUE TITLE
Sponge permission service queries Mojang Servers when creating EntityPlayerMP even in offline mode!

### ISSUE THREAD

**Issue by zyczu1** [SpongePowered/SpongeCommon#162]
Stacktrace: http://pastebin.com/VMZfAWG6

I don't know what is the purpose of doing so even on a online mode server, because when EntityPlayerMP is contructed, the GameProfile contains both name and UUID...

Mojang servers should never be queried in offline mode. Doing so will make Sponge a premium-only server software, which woudn't be good for non-US minecraft community, where most people haven't bought the game.

**Comment by JBYoshi** [comment]
I believe this also happens when the client is not properly authenticated (e.g. development mode). This should be fixed.

Related (see comment): https://github.com/SpongePowered/SpongeCommon/issues/117#issuecomment-139068648

**Comment by progwml6** [comment]
@zyczu1 we will NEVER support users who don't own the game

**Comment by JBYoshi** [comment]
@progwml6 There are, however, two exceptions to this:
- BungeeCord requires offline mode on the server, even if you are using IP forwarding.
- When doing development, the client is not (usually) authenticated; unless you're using a custom development launcher, it's just `Player` followed by a random number.

**Comment by mcsnetworks** [comment]
When doing client-side development you can setup the IDE to pass your credentials properly through the IDE to authentication servers so that part is a non-issue.

**Comment by mcsnetworks** [comment]
And to be perfectly honest if your spending the time to work on a game you haven't paid for, don't be expecting any support of any kind from the Sponge Team.

**Comment by mcsnetworks** [comment]
BungeeCord doesn't require offline, so defeated on that point too.

**Comment by JBYoshi** [comment]
@mcsnetworks Is there some modification to Sponge that skips the encryption request stage when Bungee is enabled? Because Bungee doesn't support encryption requests as it doesn't know the client's access token.

Also, you might want to test with multiple users on one server, and if you only have one account, that wouldn't work.

**Comment by ST-DDT** [comment]
You may also need different usernames or ids.
Image implementing a game with a global highscore showing the top ten players and you have only one username to test.

**Comment by zyczu1** [comment]
@progwml6 "@zyczu1 we will NEVER support users who don't own the game"
@mcsnetworks "if your spending the time to work on a game you haven't paid for, don't be expecting any support"

I DO own the game, but players on my server do not, and they'll never do so. They'd rather quit playing. Sad but true. There are other countries in the world than USA, countries where people don't have much money, and/or are not willing to spend them on a game. THATS A FACT! 

Take a look at mcstats:
http://mcstats.org/global/#Auth+Mode
Half of the community is running in offline mode. Like it or not, it is the piracy, that made Minecraft what it is today, as popular as it is today. Stripping away half of the community is not a good idea.

I have no idea why do you fight with offline mode so badly. As far as i'm concerned, you are not affiliated with Mojang and you don't get money from them for making Sponge. 

I'm not asking you to support piracy in public. I also DO think people should buy the game if they enjoy it. I'm just asking you to make Sponge work on offline-mode. You can write on yours website is not supported, etc. but please make it work!

Running offline mode server is not a violation of copyright. Playing on it with cracked minecraft is. Bukkit wasn't shut down because it worked on offline mode. That is not true!

Please :D

**Comment by Mumfrey** [comment]
Regardless of the reasons, offline mode exists in the base game so we should support it. Arguments about the ethics of it are basically irrelevant to whether a bug exists or not and frankly we shouldn't be so rude as to assume that everyone who wants to run an offline server is a pirate - that's between them and Mojang and has precisely nothing to do with us. While we obviously won't provide support (in the "helping out" sense) to people who haven't bought the game, we should *support* (in the functionality sense) all functions in the base game. Thus this:

> we will NEVER support users who don't own the game

and this:

> And to be perfectly honest if your spending the time to work on a game you haven't paid for, don't be expecting any support of any kind from the Sponge Team.

are true, but aren't actually a reason for rejecting the issue itself, and frankly could have been delivered with more decorum. Also

> BungeeCord doesn't require offline, so defeated on that point too.

... seriously ... "defeated"? Why so confrontational? All of these points are basically turning the counterpoint to the original issue into a [genetic logical fallacy](https://yourlogicalfallacyis.com/genetic) where you're attacking the idea of offline mode servers effectively encouraging piracy (which frankly is nothing to do with us) rather than actually just tackling the issue at hand, which is that something is happening in the software which shouldn't.

Now part of the blame lies with @zyczu1 because his stated reasoning referenced this behaviour, but that still doesn't justify the rude and dismissive responses here. Especially since he goes on to say:

> I have no idea why do you fight with offline mode so badly. As far as i'm concerned, you are not affiliated with Mojang and you don't get money from them for making Sponge. Or maybe i'm wrong, and some copyright lobby has paid you for the anti-offline-mode policy. If that's the case, I hope you have courage to say it aloud, to each and every member of the community. If not, I see no logical explanation for fighting against offline mode.
> 
> I'm not asking you to support piracy in public. I also DO think people should buy the game if they enjoy it. I'm just asking you to make Sponge work on offline-mode. You can write on yours website is not supported, etc. but please make it work!
> 
> Running offline mode server is not a violation of copyright. Playing on it with cracked minecraft is. Bukkit wasn't shut down because it worked on offline mode. That is not true!

Couldn't agree more, this is functionality in the vanilla server, and getting sanctimonious about the ins and outs of offline mode servers really has absolutely no bearing on it whatsoever. We should accept this issue.

**Comment by Zidane** [comment]
@Mumfrey 

This started out on the wrong foot and would have been best to let it drop as we've been aware of this bug for a while, just no one has got around to fix it.

If you look at the activity tracker, you'll see that @simon816 has been working on resolving this to correctly poll perms when it should be done:

https://github.com/SpongePowered/SpongeCommon/commit/c0f971d6bd7c3c00740f98bcb35cbaecbeda310c
