### ISSUE TITLE
Excessive arrows causing Stack Overflow crash

### ISSUE THREAD

**Issue by MoeBoy76** [SpongePowered/SpongeCommon#169]
A player has built a death trap with 10 dispensers filled with arrows in the following pattern
`| D | P | P | P | P | P | D | ` 
D = Dispenser, P = Pressure Plate
each row has an individual redstone signal so both dispensers fire when a player walks across

The only problem with this contraption seemed to be a little bit of lag due to how many entities are spawned until the server crashed with a stack overflow due to constant use of `ProjectileSourceSerializer.java:66`
https://gist.github.com/MoeBoy76/e36fbf6141d4e8c35f9f

**Comment by JBYoshi** [comment]
Here's the problem. It happens when one of the chunks containing the arrows loads:
- The `World` tries to load the chunk.
- The `Chunk` tries to load the `Arrow`.
- The `Arrow` tries to load the `ProjectileSource` via the `ProjectileSourceSerializer`.
- The `ProjectileSourceSerializer` tries to get something from the `World`.
- The `Chunk` hasn't been registered with the `World` yet (since it hasn't finished loading), so the `World` tries to load the `Chunk`.
- The `Chunk` tries to load the `Arrow`.
- The `Arrow` tries to load the `ProjectileSource` via the `ProjectileSourceSerializer`.
- The `ProjectileSourceSerializer` tries to get something from the `World`.
- The `Chunk` hasn't been registered with the `World` yet (since it hasn't finished loading), so the `World` tries to load the `Chunk`.
- The `Chunk` tries to load the `Arrow`.
- The `Arrow` tries to load the `ProjectileSource` via the `ProjectileSourceSerializer`.
- The `ProjectileSourceSerializer` tries to get something from the `World`.
- The `Chunk` hasn't been registered with the `World` yet (since it hasn't finished loading), so the `World` tries to load the `Chunk`.
- And so on...
- Until the JVM gives up and throws a `StackOverflowError`.

**Comment by simon816** [comment]
I can see why this is happening. Ultimately it's because `AnvilChunkLoader.loadEntities` loads entities __first__ then tile entities __second__.
When the Arrow entity is loaded and reads from NBT, [`ProjectileSourceSerializer`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/entity/projectile/ProjectileSourceSerializer.java) discovers the `projectileSource` tag and proceeds to loading the `ProjectileSource`. In this case, the NBT tag is a `NBTTagLong` because it's a `BlockProjectileSource` so it will [load the tile entity](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/entity/projectile/ProjectileSourceSerializer.java#L66) at that position. Problem is, tile entities are not yet loaded (due to load order in `AnvilChunkLoader`) so MC will try loading the chunk again, thus an infinite loop.

The thing I don't know is how to resolve this (yet).

**Comment by DDoS** [comment]
Mark chunks that are in progress of loading and ignore these when a load request is received?

**Comment by simon816** [comment]
I could easily add a check for `worldObj.isBlockLoaded(pos)` and don't load the tile entity if it's not loaded, but then there needs to be a way to set the projectile source on the arrow once the tile entity becomes available.

**Comment by bloodmc** [comment]
@MoeBoy76 Please upload a test world where the issue can be reproduced.

**Comment by MoeBoy76** [comment]
it should crash instantly when you load it up, which should make for a quicker debug
http://moeboy76.com/downloads/arrowcrash.zip
