### ISSUE TITLE
Custom naming of DefaultConfig, or maybe just an internal rename?

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeCommon#26]
I personally would love my plugin's config to look like something nice ("config.conf") but for defaultconfig, it's impossible to set.

**Comment by RobertHerhold** [comment]
So just follow my logic for a little bit. If you have the annotation `@DefaultConfig(sharedRoot = true`, then that means your config will be put in the `config` folder, along with every other plugin's configuration. Assuming everyone's plugin's sharedRoot value is true, then everyone's configuration will be placed in the same folder. Therefore, it would make sense that they would be identified as `myPluginName.conf`, rather than something generic like `config.conf`, which gives absolutely no indication as to what plugin it belongs to. Granted, if you have `sharedRoot` set to false, this is less of an issue, as it is placed in a folder named after the plugin. 

If you would really like to, you *can* specify a `File` named the way you want and use Configurate to use that as the configuration, but it does not make any sense for the default file name to be `config.conf`. If this were the case, everyone's configurations would turn out as `config.conf` in the same folder, and it would be a gigantic mess differentiating the configurations, not to mention issues with overwriting files.

**Comment by MikaalSky** [comment]
@RobertHerhold It wouldn't need to be a fixed name, it could be set by the plugin's creator, or possibly toggled manually between config.conf and PluginName.conf

**Comment by RobertHerhold** [comment]
But you were suggesting `config.conf` be the **default** configuration name, correct?

**Comment by boformer** [comment]
I like ``plugin-id.conf``.

You can still create individual configs with different names.

**Comment by MikaalSky** [comment]
It would be great if we could change the **default** name to config.conf.

**Comment by RobertHerhold** [comment]
Do you see the issue with that? You can't build a system in which there are conflicts **by default**. If the default for everyone's plugin is `config.conf`, then you'll have tons of issues with conflicts and overwriting files, like I mentioned above.

**Comment by Zidane** [comment]
Closing this as it will rename the plugin-id.conf. No reason to rename it.
