### ISSUE TITLE
Event PlayerDropItemEvent is not triggered upon death.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#27]
Event ```PlayerDropItemEvent``` is not triggered upon death.
Behavior is for player death to drop all items at once.
CODE:
```
   @Subscribe
    public void drop (PlayerDropItemEvent event){
        Player player = event.getPlayer();
        Collection<ItemStack> droppedItems = event.getDroppedItems();
        int size = droppedItems.size();
        player.sendMessage(Texts.of("Drop - " + size));}
```

**Comment by simon816** [comment]
This should be an issue with Sponge or SpongeVanilla rather than SpongeCommon

In Sponge, the event is mixed-in to Forge's `ItemTossEvent` (see [`MixinEventPlayerDropItem`](https://github.com/SpongePowered/Sponge/blob/865d6ffbe0e7a339ae848f63047050b08ecc53ac/src/main/java/org/spongepowered/mod/mixin/core/event/player/MixinEventPlayerDropItem.java#L43)). It looks like the event is only fired when a player throws an item (i.e. with 'q') and not on death.
In SpongeVanilla, the event is not being triggered anywhere.

**Comment by Azatik** [comment]
I am writing here, when i do not know where to write.

**Comment by modwizcode** [comment]
I'll take a look at this in SpongeVanilla

**Comment by gabizou** [comment]
I somehow doubt this is an issue anymore, confirmation @bloodmc and @Zidane ?

**Comment by Zidane** [comment]
Already implemented.
