### ISSUE TITLE
Question: Moving DataProcessor.with() and DataProcessor.fill()

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#279]
`DataProcessor`s appear to be primarily intended for moving `DataManipulator`s in and out of `DataHolder`s. However, there are two methods that aren't related to this, and they can be annoying for modders who want to integrate with Sponge:
* `Optional<I> with(Key<? extends BaseValue<?>> key, Object value, I immutable);`
* `Optional<M> fill(DataContainer container, M m);`

Could they be moved to the `DataManipulator` classes?

**Comment by gabizou** [comment]
> Optional<I> with(Key<? extends BaseValue<?>> key, Object value, I immutable);

Is used [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/manipulator/immutable/common/AbstractImmutableData.java#L144).

And `fill` is used as a delegate for building data. The only thing people have to do is just return `Optional.empty()` since they can safely ignore them. This isn't hard to do and this is why multi-processor handling does what it does, the first processor (usually sponge) will return a non-empty `Optional`. The rest can safely just return empty and be on their merry way.

**Comment by JBYoshi** [comment]
Thanks for clarifying.
