### ISSUE TITLE
"Ocelot" alias for the entity types in addition to the "Ozelot" id.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeCommon#326]
Add a alias that allows the ocelot entity type to be retreived by using "ocelot" instead of "ozelot".

**Comment by ST-DDT** [comment]
Well you could just use the `item` instead of `minecraft:item` to get the type.
Or do I miss the point here?

IMO it should return the correct values for both.
Thats why I had the following hint in my Improve CatalogType PR.
`"The GameRegistry [..] return values for well known aliases"`

**Comment by Cybermaxke** [comment]
inside the getById() method is the "item" string to converted to "minecraft:item", but the mappings map only contains "item" as the key.

**Comment by Cybermaxke** [comment]
@ST-DDT Nvm, the problem is that you need to use "ozelot" to get the "ocelot" type and that makes it a bit confusing, so the alias system would be nice for this purpose.

**Comment by simon816** [comment]
This shouldn't be a problem because of this code: https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/type/EntityTypeRegistryModule.java#L191-L194


For me, `System.out.println(Sponge.getRegistry().getType(EntityType.class, "item"));`
prints: `Optional[SpongeEntityType{id=1, name=item, modid=minecraft, class=net.minecraft.entity.item.EntityItem}]`
