### ISSUE TITLE
Player spawning in unloaded world creates new world

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeCommon#419]
What went wrong
---
If a player played on a world which gets removed while he is disconnected, a new world called ``Overworld`` will be created and the player spawns there. 

related thread on the forums: https://forums.spongepowered.org/t/unloaded-worlds-offline-players/10661

What i expected to happen
---
The player should spawn in either: 
* a special respawn world specified in some plugins config
* on the ``respawnworld`` specified for the unloaded world
* on a default world which gets specified by Sponge

How to reproduce:
---

1. load an additional world (here: ``MineCon``)
2. ``/tp`` yourself to ``MineCon``
3. disconnect
4. someone else unloads ``MineCon`` via some plugin while you're disconnected
5. reconnect
6. ``Overworld`` gets created, you spawn there instead of ``MineCon``, same coords as when you left

**Comment by TBlueF** [comment]
I think the problem is, that every world including the in `server.properties` defined world, can be disabled with sponges per-world configs..

Maybe you need **one** defined world/dimension that cannot be unloaded and will be used if an expected world is not available *(disabled or deleted)*.

Without such a defined *main* world, there is always the case: *every world is disabled, where does this player spawn now?* ^^

Also: If the target world of a portal *(or maybe `Teleporter`, i don't know what you've planned with that api)* is not available, it simply should not work. Does it?

What is the current plan here? :)

**Comment by Zidane** [comment]
@TBlueF 

You can't disable the overworld (DIM0 or the name you specify in server.properties) and I've already fixed this locally :p.

**Comment by TBlueF** [comment]
@Zidane Thaaat's what i like to hear! :p ;)
