### ISSUE TITLE
Animals Won't Follow

### ISSUE THREAD

**Issue by jasendorf** [SpongePowered/SpongeCommon#496]
spongeforge-1.8.9-1722-3.1.0-BETA-1136.jar
forge-1.8.9-11.15.1.1722   multiplayer server

Offer a chicken seed and it will not follow, pig a carrot, same.  Inscrutable noticed the same behavior in SpongeVanilla.

Perhaps related, When feeding seed, animals will breed but do not show hearts.

**Comment by simon816** [comment]
I can confirm this bug.
It appeared between SpongeForge 1131 and 1132 (https://github.com/SpongePowered/SpongeForge/commit/cbd5e0c9d8ee62499a3873c95bc67f3852e702dd)
so must be caused by something in these changes: https://github.com/SpongePowered/SpongeCommon/compare/96f62a1541d3008dc8d86be010294239e04a59b8...318d10252f86453f59bf4a3f949ab83763fd89b3
