### ISSUE TITLE
Provide a sub-command off /sponge to get a list of plugins

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#50]
It would be a huge plus to have a command (`/sponge plugins` or similar) to get a list of plugins currently active. It would be permission-based like the rest of the `/sponge` commands (currently only implemented in Sponge).
This command is helpful when helping users with issues (conflicting plugins, etc), and is much more reliable than someone manually typing a list of plugins (spelling issues, missing parts of a plugin name, etc)

@Zidane said he wasn't sure about adding this, but didn't specify a reason why (as far as I saw).

(replaces https://github.com/SpongePowered/SpongeAPI/issues/702#issuecomment-106102698)

**Comment by zml2008** [comment]
I think this would be useful to have, along with a /sponge version <plugin> -type command.

Though, this could also appear within the help system.

**Comment by ST-DDT** [comment]
A nice utility command that would help us supporting user issues would be useful as well.
 * /sponge dump

This command would print all `Platform` details (to the console) and this details could then be added/copied to the error description. And it would already contain all useful information about the platform. And a list of plugins (maybe with their version number as well.
I we have a well known (single) command for it will be easier to obtain those information and since the most popular error is "plugin/mod/sponge is incompatible with the server/sponge/other plugin" version we could provide fast help.
It could also be added to some issue template shown when creating a new issue.

````md
#Error Description:
Foo and then Crash
#Stacktrace if available
Caused by Bar
#Platform dump (Use `/sponge dump` to get this)
SpongeVersion: 42
SpongeAPIVersion: 42
Required Forge Version: 1.2.3.4
Active Forge Version: 1.3.5.8
Plugins: A,B,C
#Steps to reproduce
1) Start Server
2) Player Joins
3) Exception
````

**Comment by kashike** [comment]
@ST-DDT I like the sound of that, good thought.

**Comment by zml2008** [comment]
@ST-DDT I have that in PEX. Nobody reads the template, they just post the unfilled-out template as an issue (still provided more info than usual). I'll take a look at migrating that reporting system into Sponge at some point (it's on my to-do list), probably in addition to Sponge's existing error reporting facilities.

**Comment by ST-DDT** [comment]
So did you discard the `/sponge dump` command idea?
I agree with you that normal users will not use the template or post the dump command on issue creation. But if you explicitly ask them to post the results they usually do this.

**Comment by zml2008** [comment]
Generating error reports on request will be part of the system.
