### ISSUE TITLE
Error Key BOOK_PAGES Beta 246

### ISSUE THREAD

**Issue by rexbut** [SpongePowered/SpongeCommon#509]
Hi,
the result of the Key.BOOK_PAGES on ItemTypes.WRITTEN_BOOK and ItemTypes.WRITABLE_BOOK is not the same format.
Test code https://github.com/rexbut/EverEssentials/blob/master/EEBook.java

**Comment by Aaron1011** [comment]
The underlying problem is that while written books can use json-formatted text, the 'Book and Quill' or  writable book only supports literal, unformatted strings. There are two ways to fix this:

1. Support `PagedData` for both types of books, but serialize the plain content of each of the `Text` objects when dealing with an editable book. This has the advantage of not requiring two different `DataManipulators`, but the disadvantage of possibly breaking the contract of the manipulator in question.

2. Create a separate data manipulator (possibly `PlainPagedData`), which stores a list of strings, instead of texts. While this complicates the API for end users, it makes the limitations of editable books clear, and avoids any problem with serialization or deserialization.

**Comment by rexbut** [comment]
It would be better to support "PagedData" for both types of books

**Comment by dualspiral** [comment]
Just come up against this now too (see #1198) - it's something I would like to see fixed too!

I personally disagree with this keeping it the same API. Sponge should be representing what is available, and using such data misrepresents this, as @Aaron1011 correctly notes. It caught me out, as I hadn't realised that books were two different types, precisely because it was using the same API. 

I would argue that you should be providing a different data manipulator and key to support this.
