### ISSUE TITLE
LaunchProjectetile, Item Dropping, and Entities spawned by command do not follow new SpawnCause conventions

### ISSUE THREAD

**Issue by SocraticPhoenix** [SpongePowered/SpongeCommon#581]
Simply put, calling the method "launchProjectile," dropping an item with 'q' or using the /summon Command throw errors that say that the root Cause must be a spawn cause. I'm not sure if this is coming in #502, but I couldn't find an issue, so here you go.

Edit:
Not sure if it's helpful, but the /summon and q actions still complete (the item is dropped, or the entity is summoned), but launchProjectile doesn't actually launch anything.

**Comment by gravityfox** [comment]
Can confirm with @Aaron1011.

**Comment by modwizcode** [comment]
Taking a look

**Comment by modwizcode** [comment]
This is caused by [ProjectileLauncher](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/entity/projectile/ProjectileLauncher.java) creating the causes wrong. Instead of using a SpawnCause, it creates a named cause with the entity as the root source. There are many ways to patch this, but @gabizou I would like to know what you think is the best solution.

I am leaning towards taking the `checkSpawnCause` call out of the static `doLaunch` method and checking if the cause is an `instanceof Living` then wrapping the cause in a `SpawnCause` as appropriate. The other possibility is to duplicate similar logic in all the individual `ProjectileLogic` implementations. I don't really like either approach, since inheritance would be the ideal solution, however the implementation of the class makes the inheritance based approach seemingly impossible.

**Comment by modwizcode** [comment]
Going to leave this to https://github.com/SpongePowered/SpongeCommon/pull/502 or at least until that is done. Since there are massive changes there.

**Comment by bloodmc** [comment]
This does not occur in latest build.
