### ISSUE TITLE
Let users know about /page next and /page prev commands in paginations

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeCommon#592]
Perhaps with a notice on the first page (but not later pages to reduce noise)

Users should have the option to disable this as well (though that's not super important)

Another thought:  
```
+zml | maybe in the bottom the commands could be given like === (/page prev) << 1/n >> (/page next) ===     
```

**Comment by DarkArc** [comment]
I actually think the pagination stuff should use fixed page numbers for it's forward and back arrows. It's kind of weird when you get multiple pagination views up. For instance, if you've moved to page three, then click on page one's right arrow, you end up at page four instead of page two, which is what you might expect.
