### ISSUE TITLE
Automated detection of World etc. objects from non-Server thread, and rejection with "invalid thread access exception"

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/SpongeCommon#608]
Based on my learning in https://github.com/SpongePowered/SpongeCommon/issues/607, and fully understanding https://docs.spongepowered.org/master/en-GB/plugin/scheduler.html, just as a suggestion for a future enhancement:

How about Sponge would automatically detect when a plugin accesses World etc. objects from any non-Server thread, and reject that with some sort of "invalid thread access exception", with a pointer to saying "Dude, submit what you are trying to do in this thread as a synchronous Task into the Scheduler API" kind of hint.

Some UI framework(s), e.g. SWT, do this and it's "handy". Not critical, certainly - once you understand it.

**Comment by ewized** [comment]
An exception will be bad as there are times that one can safely access the world on a different thread.

**Comment by kashike** [comment]
:-1: As what @ewized said above. I wouldn't call this "handy" at all, I'd call it annoying.

**Comment by Deamon5550** [comment]
We could have it behind a default false flag as something to enable if you think you are accidently accessing the world from off thread somewhere. We wouldn't want it enabled by default for the reasons above and just plain performance.

**Comment by gabizou** [comment]
@Deamon5550 I think it'll be better to have it as a pure mixin plugin toggle, because almost all the world methods really don't need an extra if check that is a basic world configuration check. I feel something like this should be all or nothing. Not in between.

An additional thing is that most of the World API related methods should only apply to `WorldServer`, which coincidentally is applicable to the local SP server and of course, the server side world. Client worlds that are available specifically for rendering, shouldn't have the API methods even remotely possible to be casted.

**Comment by Deamon5550** [comment]
@gabizou A mixin plugin is what I meant when I said a flag. (is there any other way heh)

**Comment by Zidane** [comment]
Closing this until it starts becoming an issue.

@vorburger 

I won't stop you from issuing a PR with a mixin plugin to toggle this on.

**Comment by gabizou** [comment]
Likewise, with the changes in API 5.0.0-SNAPSHOT, there isn't much room for a scheduler to make changes to the world without the `CauseTracker` knowing about those changes (unless you go and bypass sponge's API entirely to use implementation based methods, which is not at all going to work in most cases).
