### ISSUE TITLE
Command usage does not display sub command arguments

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/SpongeCommon#622]
Command arguments for sub-commands do not display at all in the help message when a user types in a sub-command without the required arguments. A detailed explanation can be found below.

Command `/main` has a sub-command `set`. The sub-command `set` has a required argument, called `arg1`. Running `/main set`, without submitting the required argument, displays an unhelpful usage message: `Usage: /main set`. It fails to display the required argument, `arg1` in the usage message.

The command was created by implementing the `CommandExecutor` and registering a `CommandSpec.

**Comment by ZephireNZ** [comment]
Can you show your code for the relevant `CommandSpec`s?

**Comment by dualspiral** [comment]
I think this is actually an API issue, so should be filed there.

To explain: the issue isn't anything to do with the specific `CommandSpec` @Flibio wrote, so it would be unnecessary to see his code. I see it too with the child commands I've been writing. It's to do with what happens when parsing arguments on child commands built up by a `CommandSpec` throw an exception. Specifically, if [this line](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/ChildCommandElementExecutor.java#L140) throws an exception when parsing the child arguemnts, it bubbles up to [here](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/spec/CommandSpec.java#L330) on the base command, and the command calling method only sees an exception that could have come from anywhere in the command path, not that it came from the specific subcommand, so it just shows the usage of the parent command.

Not sure what the best solution is, unfortunately (I had a look a little while ago) - but I figured I'd at least explain the problem... never thought to report it though!

**Comment by Flibio** [comment]
Moved to https://github.com/SpongePowered/SpongeCommon/issues/622
