### ISSUE TITLE
Human Entity Issues

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeCommon#63]
Here are some issues I have found with the human entity
- [X] = Solved

~~They don't persist across server restarts.~~ - All mobs
- [x] When quitting and rejoining the entities lose the skin set originally
- [x] Setting AI goals on SpongeHuman works, but pathing doesn't so most AI is useless.

The last one might be a mistake of how I'm writing that code.

**Comment by Zidane** [comment]
A. They are MOBS and are removed when chunks unload. The API needs to be able to toggle this (but should be a feature across all entities).

B. This is because your client is really slow at rendering (bad computer?). There is an option on the server to change the time before we remove them from the PlayerList. See https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/configuration/SpongeConfig.java#L77

C. My AI worked fine. Paste some code and I'll tell you where you are wrong.

**Comment by modwizcode** [comment]
B is not the case. Computer is fine, only happens after disconnect and
rejoin. Could the same issue happen I'd the system is too fast?

**Comment by Zidane** [comment]
@modwizcode 

Doesn't happen for me. Again, back to the same point...your client is being told to remove the player list entries before it can cache the GameProfile in the client.

**Comment by modwizcode** [comment]
Alright I'll look into it. Maybe I'm just on an outdated build. Can you
post your code for AI? All I'm doing is casting back to SpongeHuman
clearing the task list and adding a new task before spawning the entity in.

**Comment by Zidane** [comment]
@modwizcode 

I don't have it handy. I need to see your code. Also, there is no such thing as SpongeHuman...

**Comment by modwizcode** [comment]
Hmm I'm not looking at my code it was probably EntityHuman in that case.

**Comment by simon816** [comment]
@modwizcode Are you still having issues?

**Comment by modwizcode** [comment]
I'm still on vacation and haven't pulled to test. I'll check this on Monday.

**Comment by modwizcode** [comment]
Seems fixed.
