### ISSUE TITLE
BungeeCord support

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#65]
Sponge (overall) has no BungeeCord/proxy support.

__Existing implementations for reference:__

*Vanilla*
http://www.spigotmc.org/resources/vanillacord.952/
https://github.com/thinkofdeath/vanillacord/blob/master/src/main/java/uk/co/thinkofdeath/vanillacord/util/BungeeHelper.java

*CraftBukkit/Spigot*
https://github.com/OvercastNetwork/SportBukkit/blob/real1.8/CraftBukkit/0004-Make-AsyncPlayerPreLoginEvent-more-versatile.patch
https://github.com/OvercastNetwork/SportBukkit/blob/real1.8/CraftBukkit/0005-BungeeCord-Support.patch

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0054-Fire-PreLogin-Events-in-Offline-Mode.patch
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0055-BungeeCord-Support.patch

https://github.com/SpongePowered/SpongeDocs/issues/258

**Comment by Tzky** [comment]
Sponge currently has no official bungeecord support, yes. But but can you currently setup a sponge or spongevanilla server that makes use of bungeecord (even if unsupported) or does everything literally break?

**Comment by ST-DDT** [comment]
Yes that should work.
There are the same issues you had with CraftBukkit. Wrong Client IP, cannot easyly teleport between Servers etc.

**Comment by dualspiral** [comment]
What you are really asking for is support for IP/UUID Forwarding - rather than BungeeCord supporting Sponge - and it's a more wide ranging problem than you think.

Simply put, as it stands, Sponge works just fine with BungeeCord unless you rely on the user's UUID and actual IP.

@me4502 has already aired this at https://github.com/SpigotMC/BungeeCord/issues/1328 - much of the reasoning why this hasn't happened is in there - but it's important to note that Bungee is written with Spigot in mind. I've already had to write a patch to allow 1.8 FML clients to join (https://github.com/SpigotMC/BungeeCord/pull/1318), and only in the case that IP forwarding is off.

If we were to just add the data to the host packet and a FML enabled client tried to join, Spigot servers would fail, thanks to one of the patches you show above. Mutating a current packet is also fragile - if the base packet form changes, then the mutations will be affected. As suggested by Lex in the linked issue, we should really think about creating custom packets and hijacking the login protocol instead of mutating the handshake packet's max length - I'm fully supportive of this option and have been playing about with a fork of Bungee and trying to create a mod that uses Mixins to see what I can do (though I'm struggling to get the mod's Mixin to load properly at the moment alongside Sponge - but that's all an aside).

Regardless, full compatibility with BungeeCord across all server implementations would require cross-party support.

**Comment by bloodmc** [comment]
@kashike I'll be pushing support for IP/UUID Forwarding as @dualspiral mentioned shortly. Everything is working properly in my workspace so stay tuned =)
