### ISSUE TITLE
Incorrect cause (intermittently) for blocks dropped during tnt explosion.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#741]
Testing on SpongeForge 1.8.9 https://github.com/SpongePowered/SpongeForge/commit/992e12156c999221b09fda2e8006c9bdcd5fc86a

I get spurious block drops with a BlockSpawnCause that has a BlockSnapshot of air.

Example shown after some grass was exploded using tnt on an obsidian platform for testing.

![image](https://cloud.githubusercontent.com/assets/141554/15457916/1c1e17b0-20d2-11e6-941f-efe3f27a5c69.png)

This does _not_ happen every explosion.

**Comment by ryantheleach** [comment]
```
@Listener(order = Order.LATE)
    public final void onBlockDrops(final DropItemEvent.Destruct dropItemEvent, @Named(NamedCause.SOURCE) final BlockSpawnCause cause) {
        final BlockSnapshot snapshot = cause.getBlockSnapshot();
        //Saw the block be randomly air once, Trying to track this down.
        assert ! BlockTypes.AIR.equals(snapshot.getState().getType());
        dropItemEvent.setCancelled(this.pendingMends.shouldCancelDropsFor(snapshot));
        if (!dropItemEvent.isCancelled()) {
            Sponge.getServer().getBroadcastChannel().send("Dropped item cause = ", Text.of(cause.toString()));
        }
    
```

Note the glass in the image is placed instead of grass during healing for debugging purposes.

**Comment by modwizcode** [comment]
I'll take this one

**Comment by modwizcode** [comment]
Alright this is a nasty one. 

The cause is easy to find. When an explosion block break drops, the drop is handled differently from pretty much every other block, this is how explosions have a variable yield than a traditional block. However the spawned entity happens before the break itself, and not as part of the chain of a normal block break. Which means that when the `BlockSnapshot` is needed for the break cause (because it's not captured as a bulk break), the entity position is used as the source of the BlockSnapshot which during a natural drop has some offset causing the snapshot to sometimes be off the area of the block by the post-tick capture.

More detailed:
The architecture for tracking item drops does not properly interact with the system that handles entity block drops and breaks. The system assumes all drops happen as a **result** of the broken block. Whereas in an explosion the drop and the block break are more accurately represented as both results of the **explosion**, with the dropped item additionally having a reference to the `BlockSnapshot` that dropped it. Since drops are fully separable from breaks with an explosion.

The approach I'm going to take is to special case the code path for dropping the item from the explosion to attach both the proper cause chain and skip the block break capture chain. The explosion can capture the block breaks as a full group.

**Comment by modwizcode** [comment]
@bloodmc I'm currently extremely busy with Google Summer of Code, so if you can take a poke or assign someone I think that would be in the best interest of getting this completed quickly.

**Comment by Zidane** [comment]
@gabizou 

Thoughts?

**Comment by gabizou** [comment]
This should be resolved after the heavy refactor of explosions and how they are processed. Granted one of the issues with the current processing is some notifications are not being fired in SpongeVanilla, which leads me to believe this issue itself is fixed.
