### ISSUE TITLE
ChangeValueEvent Proposal

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeCommon#742]
This is more me typing this up for @Zidane.

ChangeValueEvent will happen any time a value is changed. Values will be mapped to their associated data parameter which was a system added in Minecraft 1.9. 

We will need to add a new phase to the cause tracker that occurs at the end of the tick that will basically fire this event for all the data parameters whose values are being written to the client. This kind of system means that "ideally" only one ChangeValueEvent would occur per value per tick.

For example if an entity's health changes many times across the tick then we don't care for any of those values except the last one set during that tick.

Mod support is questionable but not impossible, we just have to review somehow rigging it in to this event (especially when few mods would have data API equivalent values for the data they have added to their own entities).

Any feedback is of course welcome. Any yelling can be directed to @Zidane.

**Comment by ZephireNZ** [comment]
What is the behaviour when a value is modified when called from a ChangeValueEvent?

Would this be put into the list for the next ticks list? Or would a second (third? fourth? fifth?) event be called?

**Comment by JBYoshi** [comment]
@ZephireNZ I assume that no event would be fired, as listeners that are called after a listener that changes the value will see the new value.

**Comment by JBYoshi** [comment]
I talked with @gabizou at Minecon about this. The problem with only firing one event per value per tick is that it can be changed several times with different `Cause`s. So I proposed having a single `ChangeValueEvent` subinterface for each `Key`; that way, the event can be fired multiple times per tick, and only listeners interested in that specific `Key` would receive events.

I've been busy since Minecon, though, and only got around to it this week. I began writing up some code yesterday, but then hit a roadblock today: offering `DataManipulator`s with multiple `Value`s. Ideally, they would all be fired together. Then I thought of another, very similar idea: using an event for each `DataManipulator` instead of each `Key`. It works with multiple values, and if an individual value changes, it can be wrapped in its corresponding `DataManipulator` and fired. The only requirement is that each `Key` must be tied to exactly one `DataManipulator` interface (although individual `DataManipulator`s can still have multiple values).

I'm going to go to bed now; I'll get working on some code tomorrow. In the meantime, let me know your thoughts on this.

**Comment by JBYoshi** [comment]
I'm almost done with the API side, and I have some ideas for the implementation. However, there's one problem: getting a default `Cause` when a plugin calls `offer()` without a `Cause` (the methods with a `Cause` aren't even implemented yet). SpongePowered/SpongeAPI#1370 should fix this, but it seems to have gone stale, despite being marked as a "major feature".

**Comment by gabizou** [comment]
@JBYoshi the reason for it to become stale is because we're working on pushing API 6 for a 1.11 release sooner than later. The last time that we accepted major implementation changes it cost us a few months to officially update to 1.10.2 (remember how 1.9.4 was in bleeding for a while but didn't finish?). It is definitely something we will merge in, just not at this very moment.

**Comment by JBYoshi** [comment]
@gabizou Okay. Thanks for clarifying!

**Comment by parlough** [comment]
Going to close this for now due to https://github.com/SpongePowered/SpongeAPI/pull/1728 and its implementation. If you would like changes or find problems please open a new issue with the updated state of data events.
