### ISSUE TITLE
[1.9.4] Problems with sponge plugins reload command

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeCommon#753]
The recent addition of the command ``/sponge plugins reload`` has not been without a few teething troubles.
* BUG: I can list plugins with ``/sponge plugins``, but when I click on any of the list members in-game, or eg. type ``/sponge plugins craftbook``, it executes the ``/sponge plugins reload`` command for all plugins.
This happens on the SCS, using SV Beta-315.
* In addition, it would probably be more sensible if the permission associated with it were under the sponge.command.reload hierarchy, where admins would reasonably expect it to be. ie. ``sponge.command.reload.plugins``.

**Comment by ryantheleach** [comment]
Similar problems occur on 1.8.9 on master.

**Comment by zml2008** [comment]
Yeah, we found the issue for the first part of this issue -- I mentioned it to @Zidane but it doesn't look like he pushed the fix, so I'm doing that now.

re the second part, I think under plugins makes more sense because of the command hierarchy -- it's `/sponge plugins reload` not `/sponge reload plugins`.
