### ISSUE TITLE
Canceling the SpawnEntityEvent for a block's drops stops tool degradation

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#771]
Player breaks iron with a pickaxe -> spawn of iron Item entity canceled via the SpawnEntityEvent -> the player's pickaxe doesn't degrade.

**Comment by kashike** [comment]
The tool shouldn't degrade if the block isn't dropped - it's as if it did not happen. If anything, a getter/setter to control it, defaulting to true.

**Comment by DarkArc** [comment]
The block is still broken, so something did happen.

**Comment by ryantheleach** [comment]
I think this shows a bigger issue of event chaining. When do we decide design wise when cancelling an event cancels the "stack" of future effects and when it doesn't?

Can you instead change what entity spawned instead of cancelling the event? If not this would appear to be the correct way to cancel the drop without stopping future processing, and the API should allow you to do so.

**Comment by DarkArc** [comment]
You can work around this by removing the spawned entities from inside the event.

**Comment by ryantheleach** [comment]
Then I don't see this as a bug.

**Comment by DarkArc** [comment]
How is it not a bug that an item being spawned, when cancelled does not degrade a tool? The only link here is the block.

Player breaks block -> { spawnItem, degradeTool }

Not

Player breaks block -> spawnItem -> degradeTool 

The latter makes no sense, and treating that as some kind of a chain is ONLY going to lead to confusion. There is absolutely no advantage to treating item degradation as a downstream competent of a block's drop being spawned.

**Comment by ryantheleach** [comment]
Because block drops are directly related to how the block is broken, whether it be explosion, tools, plugins, or modded tile entities.

Fortune, silktouch, and if introduced, explosion yield.

I can see your point of view, but disagree.

Whatever gets decided, it would be nice to see some semi-solid rules on how cancelling should work and effect downstream stuff, so rather then having opposing points of view, we could refer to a model to determine what the correct result should be.

**Comment by DarkArc** [comment]
Following your argument though, what happens if I cancel this event and the thing that broke the block was a block of TNT? Do we cancel the explosion?

**Comment by ryantheleach** [comment]
Under those rules it would / should halt further processing of the explosion, if it's not already happened (previous tick / stage of processing) so yes.

In my eyes cancelling is the emergency stop rewind and should effectively undo the transaction of whatever action is happening.

The problem would then be defining what an "action" is. and unfortunately might even be implementation specific details leaking.

I might be completely off base, but either there should be a concept of event chains / actions or all side effects should throw an event regardless of previous events.

Should cancelling the explosion cancel the block destroys?

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if it still occurs. We'll re-open in the event that it does.
