### ISSUE TITLE
[1.9.4] InteractBlockEvent.Secondary is fired twice when clicking on a block

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#784]
When right clicking on a block InteractBlockEvent.Secondary is fired twice.

This may be because of the new dual wielding. However, it seems even in that case, only either the MainHand or OffHand sub variant should fire.

**Comment by gabizou** [comment]
> When right clicking on a block InteractBlockEvent.Secondary is fired twice.
> 
> This may be because of the new dual wielding. However, it seems even in that case, only either the MainHand or OffHand sub variant should fire.

The problem is that the client doesn't differentiate between both hands when performing interactions. So the client will always send at least one packet, but may send a second packet, depending on the outcome of the `MAIN_HAND` being successful or not. If the main hand was not successful, the second hand (`OFF_HAND`) is sent. This is why in most all cases, there will always be a MainHand event thrown, and then if necessary, an OffHand event thereafter. Without allowing the items to process through, there's no way for the server to know in advance whether an interaction is going to only be successful with a `MainHand` or an `OffHand`.

**Comment by Aaron1011** [comment]
As @gabizou has said, there's really nothing we can do about this. The Forge interaction event has the same semantics, which means that mods are completely able to do something on one or both of the mainhand/offhand. There's simply no way we can combine these events into one, without plugins losing the ability to cancel interactions with mod items.

**Comment by DarkArc** [comment]
@Aaron1011 @gabizou I'm getting three interacts actually with right click on a block, not just two as I would expect given what you've said.
