### ISSUE TITLE
Add static methods for plugins to detect whether they're running on Forge or Vanilla

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#804]
Together with the [addition of plugin-provided mixins in SpongeVanilla](https://github.com/SpongePowered/SpongeVanilla/pull/250), it would be useful for plugins to have some static methods to detect the environment they're running in before the game has actually started.

They can be used to apply a certain mixin only to either SpongeForge or SpongeVanilla but not both (similar to what we do currently in SpongeVanilla/SpongeForge).

**Comment by Zidane** [comment]
@Minecrell 

Platform has a map of args a plugin dev can use to check for Forge (its set in SF).

**Comment by Minecrell** [comment]
@Zidane Not during the launch phase, there is nothing initialized at this point.

**Comment by Zidane** [comment]
@Minecrell 

Status?

**Comment by ImMorpheus** [comment]
See https://github.com/SpongePowered/SpongeAPI/pull/1902#issuecomment-417063950

**Comment by stephan-gh** [comment]
The implementation issue shouldn't be closed in my opinion. It shouldn't be in the API, yes, but this issue is only about the implementation in SpongeCommon. Especially considering plugin mixins load really early, most of the API is not intialized yet anyway.

Basically this should just be a simple method in the launch code provided for convenience for plugin mixin authors, obviously without guaranteed API stability like everything else in the implementation.

**Comment by ryantheleach** [comment]
I'm not 100% sure of the technical merits, but my argument for it remaining in the API, was so that it will work reliably no matter which platform implements Sponge. If there is a **technical** reason that this method can't be in the same Jar as the API, then clearly it's impossible.

> Plugin provided mixins are designed as an MCP impl feature. There is no support for them in the Sponge API, the API and its dependency set makes no guarantee that you will be able to use them. I expect that Lantern doesn’t support mixins, why would it want to use them if it has control of the full stack?

Yes, which is why the API method has **nothing** to do with mixins, aside from where it's placed inside the API jar. **Any** sort of bytecode transformation could be used, or not used.

However it would need to be placed carefully inside the API, making sure to not load any other classes.

Notes for implementors would be to make sure that the interface/class is implemented such that it can be class loaded separately to the rest of the API, due to the purpose of the method existing.

So my questions are.

1. Is it possible to implement this in the API?
2. If possible, why shouldn't it be in the API?

**Comment by dualspiral** [comment]
@ryantheleach I think there is still some confusion here about what this issue is really about - it is not an API issue and no API should be created to support this.

> If possible, why shouldn't it be in the API?

I fail to see why it _should_ it be in the API when we're trying to solve an implemention dependant issue.

This issue is a SpongeCommon issue, not an API one. It was never one about exposing this in the API. My point on the API PR was that is was the wrong place for the solution. All that did was expose an implementation detail and, crucially, does not solve this issue because of the way it was done - Mixins have not run at that point so all you're potentially doing (if you can even access API classes at this point) is getting the basic, non-transformed class... which would have just returned that the system is vanilla.

If plugins need this information during runtime, they can get the platform. They don't need another API method to do this.

If plugin provided mixins need this, they have access to the implementation already. This is just about an early marker to determine what this is.

> Yes, which is why the API method has nothing to do with mixins, aside from where it's placed inside the API jar. Any sort of bytecode transformation could be used, or not used.

[Look at the associated SpongeForge PR for that issue. It absolutely used Mixins to transform the static method that is in the API and would have forced other implementations to transform it themselves at runtime.](https://github.com/SpongePowered/SpongeForge/pull/2417/files) Big no-no.

> However it would need to be placed carefully inside the API, making sure to not load any other classes

It would need to be placed carefully in _our implementation_, making sure not to load any other classes. This issue affects MCP implementations only as the problem is that the implementations are similar for SF and SV. Other impls won't necessarily look like our impls.

As Minecrell said, it just needs to be a simple method in the launch code somewhere. If you are trying to use mixins designed for SF or SV in Lantern, they aren't going to load anyway. This is a method to aid compatibility with SF/SV/SC plugin provided mixins. They use the implementation and so might as well depend on SC at the very least.

> Notes for implementors would be to make sure that the interface/class is implemented such that it can be class loaded separately to the rest of the API, due to the purpose of the method existing.

This is leaking an implementation detail. Why should, say, Lantern do this? If someone tries to load a mixin targetting SF or SV, they are going to have bigger problems as it is, namely that it won't load in the first place.

Ultimately, the issue is to provide this information at launch for transformers. **This is not an API thing and should not be placed there.**

**Comment by ryantheleach** [comment]
> All that did was expose an implementation detail and, crucially, does not solve this issue because of the way it was done - Mixins have not run at that point so all you're potentially doing (if you can even access API classes at this point) is getting the basic, non-transformed class... which would have just returned that the system is vanilla.

I'm not arguing about the PR.

I'm arguing about one single thing.

> I fail to see why it should it be in the API when we're trying to solve an implemention dependant issue.

If it can **possibly** be standardized, it should be. That's it.

No need to look at 3 different implementations to work out how to detect them, your code for detecting an implementation can be standard, and in one place.

>Look at the associated SpongeForge PR for that issue. It absolutely used Mixins to transform the static method that is in the API and would have forced other implementations to transform it themselves at runtime. Big no-no.

If it can't be done nicely at all, then I'm happy for it to not be in the API, if it can be done nicely, I'd like it in the API. I'm not even referencing the implementation by morph.

> mixins designed for SF or SV in Lantern, they aren't going to load anyway.

Sure, but your Lantern specific module, that hooks into the implementation without mixins might like a central location to check.

> This is leaking an implementation detail. Why should, say, Lantern do this? If someone tries to load a mixin targetting SF or SV, they are going to have bigger problems as it is, namely that it won't load in the first place.

We leak much much much bigger implementation details.

**Edit:** https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/Sponge.java#L94-L102

We even already leak this exact detail, the **only** change would be making an additional one available, that won't bootstrap the rest of the classes, and that's an issue that any java program will have.

At the end of the day, the only reason I'm still arguing (I don't care that much about this topic) is so you don't question my sanity. Sometimes I really feel insulted by how heavily people dismiss my opinion, based on their opinion, without discussing the **technical** merits, as opposed to the 'soft' requirements. (Not saying you are doing this here, you have provided several **good** soft requirements.)

So I attempt to reason it to see if I was even remotely on the right page, and then get repeatedly dismissed (without a technical explanation, to improve my knowledge and the way I can contribute).

But I am still, very much legitimately interested, in whether it's **possible**, regardless of if you disagree, and regardless of whether it won't happen for soft reasons.

**Comment by gabizou** [comment]
> We even already leak this exact detail, the only change would be making an additional one available, that won't bootstrap the rest of the classes, and that's an issue that any java program will have.



> But I am still, very much legitimately interested, in whether it's possible, regardless of if you disagree, and regardless of whether it won't happen for soft reasons.

Going to just say, the entirety of SpongeAPI is not usable at mixin plugin initialization/configuration. Mixin does provide some detection of obfuscation environments, but it does not have the ability to determine platforms at such an early stage. This is why the SpongeCoreMod (and likewise SpongeVanilla launcher) don't have forge bundled into one (and why our implementations are still separated into separate repositories). It would be neat to be able to figure out the platform that early, but currently it's not even detected in any of our implementation.

To quote the `IMixinConfigPlugin` javadocs:
```
 * <p>A companion plugin for a mixin configuration object. Objects implementing
 * this interface get some limited power of veto over the mixin load process as
 * well as an opportunity to apply their own transformations to the target class
 * pre- and post-transform. Since all methods in this class are called
 * indirectly from the transformer, the same precautions as for writing class
 * transformers should be taken. Implementors should take care to not reference
 * any game classes, and avoid referencing other classes in their own mod except
 * those specificially designed to be available at early startup, such as
 * coremod classes or other standalone bootstrap objects.</p>
 * 
 * <p>Instances of plugins are created by specifying the "plugin" key in the
 * mixin config JSON as the fully-qualified class name of a class implementing
 * this interface.</p>
```

Since there's no uniform standard to say "*hey, I'm loading mixins, what platform is this*" to Mixin, it's also not something that is easy to expose during the initialization phases for the plugins because even `SpongeImpl` hasn't been initialized yet:

<img width="1545" alt="screen shot 2018-09-06 at 10 49 43 am" src="https://user-images.githubusercontent.com/1203877/45175596-ab450880-b1c2-11e8-9ef2-477e02a58125.png">

The biggest problem to detect platforms is the platforms themselves being exposed as early as mixin configuration stages, which currently, we don't have a way to do so that I can think of.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/ca9f47929531abd9a84591aca351d31d78488a41
