### ISSUE TITLE
[1.10] Blocks are not reverted when BlockChangeEvents are reverted

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#815]
When a `BlockChangeEvent` for a player breaking a block is canceled, the blocks are not restored back to their previous states.

**Comment by mcsnetworks** [comment]
This seems to be a critical issue.

**Comment by Aaron1011** [comment]
@DarkArc: The issue seems to be that you're indiscriminately cancelling the root `ChangeBlockEvent`. This causes the following sequence of events:

1. A `ChangeBlockEvent.Break` event is sent to your listener, which is cancelled
2. The CauseTracker fires a `ChangeBlockEvent.Post` event, which includes the previous cancelled event in the `Cause`, and the original transactions from the previous event in its own transactions list. This event is also cancelled
3. The cancellation of the `ChangeBlockEvent.Post` event causes the CauseTracker to restore the original non-air block. However, it calls `BlockSnapshot#restore`, which triggers <i>another</i> event - a `ChangeBlockEvent.Place` event.
4. The plugin cancels the `ChangeBlockEvent.Place` event, as well as the following `ChangeBlockEvent.Post` evnet.
5. Since the 'place' event triggered by the restoration was cancelled, the end result is that the block is broken as normal.

@gabizou: Should the `CauseTracker` be firing events by way of `BlockSnapshot#restore` as it's doing now?

**Comment by gabizou** [comment]
@Aaron1011 it should not be anymore.

**Comment by ryantheleach** [comment]
Won't this create holes in tracking plugins rollbacks?

Take Creepermend for example, lets explosions happens, logs the blocks broken, some time later they are .restored() if .restore throws no event, how is prism to know that the explosion was repaired?

**Comment by Zidane** [comment]
Should be resolved now in latest bleeding.
