### ISSUE TITLE
Chunk position methods use full block location, not relative location within chunk

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#83]
Issues occur that a `Location` for block within a Chunk, relative to the 0,0 of the Chunk since not all chunks contain 0,0,0.

**Comment by DDoS** [comment]
It was decided not to use relative positions for chunks to simplify generators (which almost always use the world coordinate space, especially for noise generation) and provide a homogeneous system across worlds and chunks, which lets you substitute the two easily. This means that the BlockVolume, BiomeArea and by extension Extent all use world coordinate space. Since Location is a pointer in an Extent, it uses the world coordinates.

**Comment by DDoS** [comment]
I'm completing the world access API after Minecon. This will allow users to get relative views from any Volume or Area

    Location location = chunk.relativeView().getLocation(0, 0, 0);
    location.getPosition() // prints (0.0, 0.0, 0.0)

The relative view could even be cached in chunks for practically zero object cost.
