### ISSUE TITLE
[1.8.9] Explosions don't fire BlockChangeEvent.Break, Also no player cause for ExplosionEvent.Detonate

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#833]
They should, and they used to.

The only event i can see is ExplosionEvent.Detonate, but I can't get the player cause from that event.

**Comment by gabizou** [comment]
1.8.9? 1.10?

**Comment by gravityfox** [comment]
1.8.9

**Comment by bloodmc** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Entity.java#L451

Why aren't you using this for the source entity? I purposely turned off capturing for explosions since it was very heavy on performance.

https://github.com/SpongePowered/SpongeCommon/commit/e53ca9f848d402c58a5ef78e975c473073945be5

**Comment by gravityfox** [comment]
Going event->explosion->explosive entity->source/notifier seems rather roundabout, even though that is an option. I just think that people would expect to get the source directly from the cause.

**Comment by bloodmc** [comment]
OK i'll add the user to the cause when I get some free time.

**Comment by Zidane** [comment]
1.8.9 is no longer supported.
