### ISSUE TITLE
SpongeTeleportHelper + slabs

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#848]
SpongeTeleportHelper probably needs to be improved to be able to deal with slabs/rails/carpets/ other ground coverers.

One way that it can be improved is to check 1 block up first, before it starts to check in a radius around the location, as after gravity takes effect they will end up in the correct position.

What would be better would be some real kind of hitbox checking, check that the block isn't on a configurable blacklist (mod support) and that the player will hit the hitbox and be able to stand there.

**Comment by Zidane** [comment]
@dualspiral @ryantheleach 

Forgot to check if this ticket is still an issue with @dualspiral 's changes. Can one of you investigate and see?

**Comment by Faithcaio** [comment]
Signs are also very unsafe it seems.

**Comment by stephan-gh** [comment]
@dualspiral Can you take a look at this issue? Is it still an issue with your refactor in https://github.com/SpongePowered/SpongeCommon/pull/905?

**Comment by dualspiral** [comment]
Yep, will put this on the pile to look at.

**Comment by dualspiral** [comment]
Looking into this:

* carpets, rails and signs are fine (signs are passable blocks, I was able to warp straight into a sign)
* half blocks and stairs are not OK, and the safe teleportation will likely move the player sideways rather than up - with the routine as it is, it _could_ teleport a player one block up, it just doesn't currently.

I just need to tweak the algorithm a bit, which I'm doing as part of a bigger change that allows plugins to determine their own criteria for whether a block is safe/floor is safe/blockstate is passable, should have a PR for this soon.

**Comment by Faithcaio** [comment]
@dualspiral Are you sure you teleported INTO a sign?
I keep getting placed above or next to it using `Player#setLocationSafely`.
`BlockSign` is `Material.WOOD`
Maybe check for IBlockProperties#causesSuffocation + Lava?

**Comment by dualspiral** [comment]
Yep, I was put into the middle of the sign, rather than beside it. Odd, as you said, that probably shouldn't have worked, probably just fell onto it.

I think I'm going to do as you suggest regardless, I've been wanting to move this away from just material based as much as possible to try and cater for mods more. I just hadn't gotten around to tweaking my kernels yet.
